name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, build, and test
      run: |
        npm install
        npm run lint
        npm run build:all
      env:
        CI: true

    - name: Deploy to GitHub Pages
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f docs
        git commit -m 'Deploy to GitHub Pages'
        git subtree split --prefix docs master -b gh-pages-temp
        git push origin gh-pages-temp:refs/heads/gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
